### PR TITLE
Add keyword coercion (Keyword symbol) in #duct/env

### PR DESCRIPTION
**Pull request by arichiardi**
Implements #38.

### CODE REVIEW

**Comment by weavejester** [comment]
Let's make it `Keyword` instead.

**Comment by arichiardi** [comment]
@weavejester anything else we need to do for merging this one?

**Comment by weavejester** [comment]
I don't get notified about new commits, so it's often worth adding a comment, otherwise I won't know if there have been changes :)

Can you change the commit message to:

    Add keyword coercion to #duct/env (fixes #38)

There's no need to add any more to the commit message.

**Comment by arichiardi** [comment]
I can definitely do that, FWIW the second part is content and won't appear in git log with `--pretty=oneline` - it is usually recommended to have head + content. In any case doing it and writing you back when done

**Comment by arichiardi** [comment]
Ok done

**Comment by weavejester** [comment]
> FWIW the second part is content and won't appear in git log with --pretty=oneline - it is usually recommended to have head + content.

I'd generally agree, but in this case it doesn't add any useful information so should be omitted.

**Pull request merged**
