### PR TITLE
Update Medley to 1.4.0

### PR DESCRIPTION
**Pull request by arichiardi**
Prevents Clojure 1.11 warnings.

### CODE REVIEW

**Comment by weavejester** [comment]
There's too many changes in this PR and the associated commit for me to merge. Can you strip back everything except for the Medley update, and change the commit message to:

    Update Medley to 1.4.0

    Prevents Clojure 1.11 warnings.

**Comment by arichiardi** [comment]
@weavejester I can definitely do that. One question, do I split the second commit too?

As far as I know clojure is never required as direct dependency and can cause problems.

**Comment by weavejester** [comment]
>  One question, do I split the second commit too?

Which second commit do you mean?

> As far as I know clojure is never required as direct dependency and can cause problems.

What problems does it cause?

**Comment by arichiardi** [comment]
> What problems does it cause?

I had conflicts in the past with transitivity but maybe those were actually solved. If you think it's not worth it I can leave it out

**Comment by weavejester** [comment]
As far as I'm aware, including Clojure as an actual dependency is the correct way of doing things, since the library depends on Clojure being present to work, and any Clojure version specified in the project dependencies will override the one specified by the library.

So all that's needed is the version change to Medley. Once the commit message is fixed, I'll merge.

**Comment by arichiardi** [comment]
I have always thought it would be a provided - kind of a runtime - dependency.

Funnily enough only at runtime you can actually check if things like the new 1.11 `(random-uuid)` is present.

Anyways, I will change the commit now. Thanks for the prompt answers

**Comment by arichiardi** [comment]
Done

**Pull request merged**
